name = "indexer"

[[tables]]
name = "swaps"
force=true

[[tables.columns]]
name = "creation"
col_type = "BYTEA"

[[tables.columns]]
name = "stable"
col_type = "BYTEA"

[[tables.columns]]
name = "stableamt"
col_type = "BYTEA"

[[tables.columns]]
name = "floating"
col_type = "BYTEA"

[[tables.columns]]
name = "numerator"
col_type = "BYTEA"

[[tables.columns]]
name = "denom"
col_type = "BYTEA"