name = "indexer"

[[tables]]
name = "storage"

[[tables.columns]]
name = "is_stored"
col_type = "BYTEA"

[[tables.columns]]
name = "envelope"
col_type = "BYTEA"

[[tables.columns]]
name = "res_meta"
col_type = "BYTEA"