name = "indexer"

[[tables]]
name = "swaps"

[[tables.columns]]
name = "created_at"
col_type = "BYTEA"

[[tables.columns]]
name = "stablecoin"
col_type = "BYTEA"

[[tables.columns]]
name = "stablecoin_amount"
col_type = "BYTEA"

[[tables.columns]]
name = "floating_asset"
col_type = "BYTEA"

[[tables.columns]]
name = "price_numerator"
col_type = "BYTEA"

[[tables.columns]]
name = "price_denominator"
col_type = "BYTEA"